### ISSUE TITLE
Remove VBA Project Locked/Unviewable Protection doesn't work

### ISSUE THREAD

**Issue by sinhthanh** [outflanknl/EvilClippy#14]
Hi team,
Thanks for release this great tool. I found one case it's doesn't work, please take a look. The files in the attachments is blocked with a tool call Unviewable+ from spreadsheet1.com
[UnviewablePlus-Samples.zip](https://github.com/outflanknl/EvilClippy/files/3288704/UnviewablePlus-Samples.zip)

**Comment by stanhegt** [comment]
@clr2of8, can you shed some light on this? Thanks!

**Comment by nkev** [comment]
After using EvilClippy to enable the VBE coe, only the **Modules** folder is hidden but you can easily fully recover that and all other VBA scripts using the publically available tool **olevba**. 
I notified Petros of this but he refused to announce this on his website. People should know that this product is not secure at all, contrary to what the spreadheet1.com site says.

**Comment by shumashv1** [comment]
He means his tool prevents EvilClippy from making any changes to the files he provided.  They remain unviewable no matter what you do to them.

**Comment by stanhegt** [comment]
Providing detailed instructions for compromising the security of specific products (in this case Unviewable+) is beyond the purpose of EvilClippy. Closing this issue.
