### ISSUE TITLE
EvilClippy not running on .doc

### ISSUE THREAD

**Issue by surajpkhetani** [outflanknl/EvilClippy#15]
Evilclippy gave errors when running on a .doc file. The error mentions that it could not find VBA, however, the sample file has a macro code and runs successfully as well. Below is the error:

```
C:\Users\user1\Desktop\Test Files\EvilClippy>..\..\..\Downloads\EvilClippy\EvilClippy.exe -r asr-bypass-word.doc

Unhandled Exception: OpenMcdf.CFItemNotFound: Cannot find item [VBA] within the current storage
   at OpenMcdf.CFStorage.GetStorage(String storageName)
   at MSOfficeManipulator.Main(String[] args)
```

**Comment by stanhegt** [comment]
Hi! It is very likely that you embedded the macro in your normal.dotm, instead of this file. Please check https://github.com/outflanknl/EvilClippy/issues/13 for a similar report. If you are confident that this is not the case, please share a sample. Thanks!

**Comment by surajpkhetani** [comment]
Thanks for the quick response. Indeed I cannot find the vbaproject.bin file in the 7zip archive as mentioned in the above reference. 
I create macro based documents by going to view --> macro -- > view macros --> edit - where i write the macro code. I think this embeds the macro in normal.dotm
Can you point me in a right direction of how i can create a macro document which includes vbaproject.bin?

**Comment by stanhegt** [comment]
In the VBA editor, make sure that in the pane on the top left you have selected a module (e.g. "ThisDocument") in your current document and not "Normal". To use all options of EvilClippy, you need to embed your code in a separate module (not "ThisDocument") in your current document/project.
