### ISSUE TITLE
After the macro virus office file "-s -t", win10 reports "sub or Function not defined."

### ISSUE THREAD

**Issue by chaiyixia** [outflanknl/EvilClippy#16]
EvilClippy.exe -s test.vba -t 2016x64 "hello.docm"

![图片](https://user-images.githubusercontent.com/38531981/61592668-04fec780-ac09-11e9-9613-a5d3a8edc89e.png)
Win10
hello.docm is sucessful，but hello_EvilClippy.docm is fail.
why? 

test.vba is
```
Sub Workbook_Open()
MsgBox "This message comes from the P-code"
End Sub
````

result
![图片](https://user-images.githubusercontent.com/38531981/61592663-f7494200-ac08-11e9-9cd4-994633ab795b.png)

**Comment by chaiyixia** [comment]
I am very sorry, I am too stupid.
The reason is that my win10 office is 32-bit

**Comment by stanhegt** [comment]
No worries. Also note that you’re using a Excel sub Workbook_Open for a Word document. That doesn’t make much sense. ;-)
