### ISSUE TITLE
Not working Serve a VBA stomped template via HTTP

### ISSUE THREAD

**Issue by chyond1** [outflanknl/EvilClippy#19]
Hello! I try to test your program, everything works fine except for Serve a VBA stomped template via HTTP. On a 2016x64 machine, I create a .doc document, insert a macro, save it as a .dot template. In the file fakecode.vba I put the first line Attribute VB_Base = "0 {00020906-0000-0000-C000-000000000046}", and then the fake vba code. I start the server, on another machine 2013x64 I open a document that loads the template over the network, the template is loaded, but when the macro starts, an error appears, the macro does not execute. What could be the problem?

**Comment by stanhegt** [comment]
Hi and thanks for reaching out. Note that serving stomped documents via templates is still an experimental feature. What error message is displayed? Does the server successfully detect the Office version of the client that retrieves the document? Is the Office install (not Windows) of both systems 64 bits (note that this is not the default for 2013)?

**Comment by stanhegt** [comment]
@chyond1 has indicated via Twitter DM that he has solved this issue.
