### ISSUE TITLE
How to specify output doc | No output option specified in readme + --help

### ISSUE THREAD

**Issue by graysuit** [outflanknl/EvilClippy#22]
Do you have any output option like<br>
`EvilClippy.exe -u input=Doc1.doc output=Evildoc.doc`<br>If not then add it in next release on my request.<br>
Please Please Please Please Please Please

**Comment by stanhegt** [comment]
Thank you for your feedback. There is currently no parameter for specifying the output file name. At the moment, EvilClippy will automatically generates a file with _EvilClippy appended to it in the name.
