### ISSUE TITLE
All office Ver

### ISSUE THREAD

**Issue by moaeddy** [outflanknl/EvilClippy#23]
Is there anyway to stomp a VBA and it works on office 2010-2016? tried different ways but not getting it to work

**Comment by stanhegt** [comment]
Unfortunately this is not possible with stomping. You have to target a detailed MS Office version + architecture in order to have the pcode executed.

You can watch the following presentation from Pieter Ceelen and myself for a more detailed explanation: https://www.youtube.com/watch?v=iXvvQ5XML7g.
