### ISSUE TITLE
ERROR: Could not open file

### ISSUE THREAD

**Issue by ca3tie1** [outflanknl/EvilClippy#30]
hello!
I create a MS Word template (.dotm) that includes a malicious macro.On a 2016x64 VM machine.
In the file fakecode.vba I put the first line Attribute VB_Base = "0 {00020906-0000-0000-C000-000000000046}", and then the fake vba code. 
when i try to run "EvilClippy.exe -s fakecode.vba -w 8080 test.dotm",there is an error i have:
ERROR: Could not open file test.dotm
Please make sure this file exists and is .docm or .xlsm file or a .doc in the Of
fice 97-2003 format.

Invalid OLE structured storage file

did i something wrong?

**Comment by stanhegt** [comment]
Similar issues submitted by others appeared to be caused by human error. ;-) If this issue still persits then please submit a sample and I'd be happy to have a look at it.
