### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by jbf21144** [outflanknl/EvilClippy#31]
Receiving a similar issue as PinkDev1....Thte thread was closed but I copied the compile error from the post

compression.cs(111,60): error CS1002: ; expected
compression.cs(111,78): error CS1519: Invalid token ';' in class, struct, or interface member declaration
compression.cs(123,25): error CS1002: ; expected
compression.cs(123,28): error CS1520: Method must have a return type
compression.cs(123,43): error CS1002: ; expected
compression.cs(123,50): error CS1519: Invalid token ';' in class, struct, or interface member declaration
compression.cs(174,49): error CS1002: ; expected
compression.cs(174,59): error CS1519: Invalid token ')' in class, struct, or interface member declaration
compression.cs(174,81): error CS1519: Invalid token '-' in class, struct, or interface member declaration
compression.cs(246,64): error CS1002: ; expected
compression.cs(246,84): error CS1519: Invalid token ';' in class, struct, or interface member declaration
compression.cs(320,28): error CS1002: ; expected
compression.cs(320,43): error CS1519: Invalid token ';' in class, struct, or interface member declaration
compression.cs(322,32): error CS1002: ; expected
compression.cs(322,47): error CS1519: Invalid token ';' in class, struct, or interface member declaration
compression.cs(445,44): error CS1002: ; expected
compression.cs(445,54): error CS1519: Invalid token ')' in class, struct, or interface member declaration
compression.cs(445,69): error CS1519: Invalid token ')' in class, struct, or interface member declaration
compression.cs(516,70): error CS1519: Invalid token '=' in class, struct, or interface member declaration
compression.cs(516,99): error CS1519: Invalid token '(' in class, struct, or interface member declaration
compression.cs(658,28): error CS1002: ; expected
compression.cs(711,25): error CS1002: ; expected
compression.cs(711,40): error CS1519: Invalid token ';' in class, struct, or interface member declaration
compression.cs(1084,38): error CS1002: ; expected
compression.cs(1084,59): error CS1519: Invalid token ';' in class, struct, or interface member declaration
compression.cs(1086,31): error CS1002: ; expected
compression.cs(1086,40): error CS1519: Invalid token '=>' in class, struct, or interface member declaration
compression.cs(1086,50): error CS1519: Invalid token ';' in class, struct, or interface member declaration
compression.cs(1124,30): error CS1002: ; expected
compression.cs(1124,43): error CS1519: Invalid token '(' in class, struct, or interface member declaration
compression.cs(1124,46): error CS1519: Invalid token '=>' in class, struct, or interface member declaration
compression.cs(1124,57): error CS1519: Invalid token ')' in class, struct, or interface member declaration
compression.cs(1126,47): error CS1002: ; expected
compression.cs(1126,57): error CS1519: Invalid token ';' in class, struct, or interface member declaration

Any idea why I would be receiving this?

**Comment by stanhegt** [comment]
I've just tested this and the code compiles without warnings or errors using the default dev VM provided by Microsoft (https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/). Make sure you use the developer command prompt! :-)

**Comment by jbf21144** [comment]
Thanks Stan, I’ll look into this!

Jason Frischkorn
Cell: (410) 707-1075
