### ISSUE TITLE
Virus Total q/a

### ISSUE THREAD

**Issue by shtry** [outflanknl/EvilClippy#38]
Hi.

This tool cannot bypass AV.

Is it normal?

```
EvilClippy.exe -urg  test.xlsm
```
virustotal:
https://www.virustotal.com/gui/file/2abd0d49585aa5df8331c350f3ebdb1477f07f890ca3955fcf22f2aeba2f3ee2/detection

**Comment by stanhegt** [comment]
Please refer to related issues such as https://github.com/outflanknl/EvilClippy/issues/36 and https://github.com/outflanknl/EvilClippy/issues/7
