### ISSUE TITLE
error  V1.3 & V1.2

### ISSUE THREAD

**Issue by leezp** [outflanknl/EvilClippy#41]
$  EvilClippy.exe -s a.vba A.doc

未经处理的异常:  OpenMcdf.CFItemNotFound: Cannot find item [VBA] within the curr
ent storage
   在 OpenMcdf.CFStorage.GetStorage(String storageName)
   在 MSOfficeManipulator.Main(String[] args)

**Comment by stanhegt** [comment]
Are you sure A.doc contains a VBA macro? Can you demonstrate this with output of olevba for example?

**Comment by leezp** [comment]
@stanhegt  
![image](https://user-images.githubusercontent.com/16287528/110565043-cc6a8380-8188-11eb-8f84-b484544acd74.png)
this tool has some problem . but it has a macro indead,has cs online .
![image](https://user-images.githubusercontent.com/16287528/110565246-21a69500-8189-11eb-86ad-d6ca0e063721.png)

![image](https://user-images.githubusercontent.com/16287528/110565147-f7ed6e00-8188-11eb-98e6-fabdffdadfd7.png)
![image](https://user-images.githubusercontent.com/16287528/110565186-06d42080-8189-11eb-85bd-78eb7bf64a00.png)

**Comment by stanhegt** [comment]
From the screenshot I can tell that you put the macro in your normal.dotm template, not in the document. Closing this issue.

**Comment by leezp** [comment]
@stanhegt thanks a lot. 
![image](https://user-images.githubusercontent.com/16287528/110727137-a3fc8b00-8255-11eb-8fc5-626cd05ea56c.png)
good effect
