### ISSUE TITLE
Couldn't find the VBA

### ISSUE THREAD

**Issue by anonuser78** [outflanknl/EvilClippy#6]
When I try to execute certain commands, it gives me the error 
![vba](https://user-images.githubusercontent.com/47336246/56905234-d50eb080-6a6d-11e9-9a1d-9c19d9e3d34c.png)

**Comment by stanhegt** [comment]
Are you sure the target file contains macros? If so, can you share the sample?

**Comment by anonuser78** [comment]
The problem is solved. Thank you 
I wonder if we can use EvilClippy in integration with Metasploit?

**Comment by leezp** [comment]
@anonuser78  can i ask how to solve the problem
