### ISSUE TITLE
Couldn't Compile (compression.cs)

### ISSUE THREAD

**Issue by PinkDev1** [outflanknl/EvilClippy#8]
After making a fresh new instalation of Visual Studio 2019 (Community edition), and attempting to compile this proyect, I get the following:

<i>
E:\Programas\EvilClippy-master\EvilClippy-master>csc /reference:OpenMcdf.dll,System.IO.Compression.FileSystem.dll /out:EvilClippy.exe *.cs

Microsoft (R) Visual C# Compiler version 4.7.3190.0
for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.

This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

compression.cs(111,60): error CS1002: ; expected
compression.cs(111,78): error CS1519: Invalid token ';' in class, struct, or interface member declaration
compression.cs(123,25): error CS1002: ; expected
compression.cs(123,28): error CS1520: Method must have a return type
compression.cs(123,43): error CS1002: ; expected
compression.cs(123,50): error CS1519: Invalid token ';' in class, struct, or interface member declaration
compression.cs(174,49): error CS1002: ; expected
compression.cs(174,59): error CS1519: Invalid token ')' in class, struct, or interface member declaration
compression.cs(174,81): error CS1519: Invalid token '-' in class, struct, or interface member declaration
compression.cs(246,64): error CS1002: ; expected
compression.cs(246,84): error CS1519: Invalid token ';' in class, struct, or interface member declaration
compression.cs(320,28): error CS1002: ; expected
compression.cs(320,43): error CS1519: Invalid token ';' in class, struct, or interface member declaration
compression.cs(322,32): error CS1002: ; expected
compression.cs(322,47): error CS1519: Invalid token ';' in class, struct, or interface member declaration
compression.cs(445,44): error CS1002: ; expected
compression.cs(445,54): error CS1519: Invalid token ')' in class, struct, or interface member declaration
compression.cs(445,69): error CS1519: Invalid token ')' in class, struct, or interface member declaration
compression.cs(516,70): error CS1519: Invalid token '=' in class, struct, or interface member declaration
compression.cs(516,99): error CS1519: Invalid token '(' in class, struct, or interface member declaration
compression.cs(658,28): error CS1002: ; expected
compression.cs(711,25): error CS1002: ; expected
compression.cs(711,40): error CS1519: Invalid token ';' in class, struct, or interface member declaration
compression.cs(1084,38): error CS1002: ; expected
compression.cs(1084,59): error CS1519: Invalid token ';' in class, struct, or interface member declaration
compression.cs(1086,31): error CS1002: ; expected
compression.cs(1086,40): error CS1519: Invalid token '=>' in class, struct, or interface member declaration
compression.cs(1086,50): error CS1519: Invalid token ';' in class, struct, or interface member declaration
compression.cs(1124,30): error CS1002: ; expected
compression.cs(1124,43): error CS1519: Invalid token '(' in class, struct, or interface member declaration
compression.cs(1124,46): error CS1519: Invalid token '=>' in class, struct, or interface member declaration
compression.cs(1124,57): error CS1519: Invalid token ')' in class, struct, or interface member declaration
compression.cs(1126,47): error CS1002: ; expected
compression.cs(1126,57): error CS1519: Invalid token ';' in class, struct, or interface member declaration </i>

**Comment by stanhegt** [comment]
It appears that you are using an outdated C# compiler (note the line on C# version 5). Are you running csc.exe from a VS developer command prompt (as stated in the readme)? If so, please check the path from which csc.exe is used.

**Comment by jbf21144** [comment]
> After making a fresh new instalation of Visual Studio 2019 (Community edition), and attempting to compile this proyect, I get the following:
> 
> E:\Programas\EvilClippy-master\EvilClippy-master>csc /reference:OpenMcdf.dll,System.IO.Compression.FileSystem.dll /out:EvilClippy.exe *.cs
> Microsoft (R) Visual C# Compiler version 4.7.3190.0
> for C# 5
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240
> 
> compression.cs(111,60): error CS1002: ; expected
> compression.cs(111,78): error CS1519: Invalid token ';' in class, struct, or interface member declaration
> compression.cs(123,25): error CS1002: ; expected
> compression.cs(123,28): error CS1520: Method must have a return type
> compression.cs(123,43): error CS1002: ; expected
> compression.cs(123,50): error CS1519: Invalid token ';' in class, struct, or interface member declaration
> compression.cs(174,49): error CS1002: ; expected
> compression.cs(174,59): error CS1519: Invalid token ')' in class, struct, or interface member declaration
> compression.cs(174,81): error CS1519: Invalid token '-' in class, struct, or interface member declaration
> compression.cs(246,64): error CS1002: ; expected
> compression.cs(246,84): error CS1519: Invalid token ';' in class, struct, or interface member declaration
> compression.cs(320,28): error CS1002: ; expected
> compression.cs(320,43): error CS1519: Invalid token ';' in class, struct, or interface member declaration
> compression.cs(322,32): error CS1002: ; expected
> compression.cs(322,47): error CS1519: Invalid token ';' in class, struct, or interface member declaration
> compression.cs(445,44): error CS1002: ; expected
> compression.cs(445,54): error CS1519: Invalid token ')' in class, struct, or interface member declaration
> compression.cs(445,69): error CS1519: Invalid token ')' in class, struct, or interface member declaration
> compression.cs(516,70): error CS1519: Invalid token '=' in class, struct, or interface member declaration
> compression.cs(516,99): error CS1519: Invalid token '(' in class, struct, or interface member declaration
> compression.cs(658,28): error CS1002: ; expected
> compression.cs(711,25): error CS1002: ; expected
> compression.cs(711,40): error CS1519: Invalid token ';' in class, struct, or interface member declaration
> compression.cs(1084,38): error CS1002: ; expected
> compression.cs(1084,59): error CS1519: Invalid token ';' in class, struct, or interface member declaration
> compression.cs(1086,31): error CS1002: ; expected
> compression.cs(1086,40): error CS1519: Invalid token '=>' in class, struct, or interface member declaration
> compression.cs(1086,50): error CS1519: Invalid token ';' in class, struct, or interface member declaration
> compression.cs(1124,30): error CS1002: ; expected
> compression.cs(1124,43): error CS1519: Invalid token '(' in class, struct, or interface member declaration
> compression.cs(1124,46): error CS1519: Invalid token '=>' in class, struct, or interface member declaration
> compression.cs(1124,57): error CS1519: Invalid token ')' in class, struct, or interface member declaration
> compression.cs(1126,47): error CS1002: ; expected
> compression.cs(1126,57): error CS1519: Invalid token ';' in class, struct, or interface member declaration

PinkDev1, 

What ended being the solution to your problem? I am having the same issues

**Comment by PinkDev1** [comment]
@jbf21144 there's no fix lol
I was never able to compile Evil Clippy

**Comment by zaza6677** [comment]
use Developer Command Prompt in VS ,and it will be ok
