### ISSUE TITLE
workbook

### ISSUE THREAD

**Issue by moaeddy** [outflanknl/EvilClippy#9]
this not hidding my macro code in workbook, doesn't work on this?

**Comment by stanhegt** [comment]
Are you trying this with the -g (GUI hide) option? Have you inserted your macro in a separate module instead of ThisWorkbook?

**Comment by moaeddy** [comment]
if i insert macro in separate module using auto_open in .xlsm and using -g option , this is still categorize as malware in office outlook

**Comment by stanhegt** [comment]
You seem to be mixing up the concept of subs and modules here. Also note that the GUI hide option does not affect AV, you will need the stomping option (-s flag) for this.

**Comment by moaeddy** [comment]
when -s option is use, normal code doesn't execute, but when -g is used normal code execute

**Comment by stanhegt** [comment]
Don’t forget to target the correct Office version (-t) when you’re doing stomping (-s).
